language: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t 1234567892018/react-test -f ./client/Dockerfile  ./client
script:
  - docker build -t 1234567892018/multi-client  -f ./client/Dockerfile   ./client
  - docker build -t 1234567892018/multi-nginx  -f  ./nginx/Dockerfile   ./nginx
  - docker build -t 1234567892018/multi-server -f  ./server/Dockerfile   ./server
  - docker build -t 1234567892018/multi-worker -f  ./worker/Dockerfile   ./worker
    #Log to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #TAKE IMAGE AND PUSH IT DOCKER HUB
after_success:
#Log to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#TAKE IMAGE AND PUSH IT DOCKER HUB
  - docker push  1234567892018/myrepo:multi-client
  - docker push  1234567892018/myrepo:multi-nginx
  - docker push  1234567892018/myrepo:multi-server
  - docker push  1234567892018/myrepo:multi-worker
