sudo: required
services:
  - docker

before_install:
  - docker build -t 1234567891993/react-test -f ./client/Dockerfile


script:
  - docker run 1234567891993/react-test npm test -- --cover

after_success:
  - docker build 1234567891993/multi-client ./client
  - docker build 1234567891993/multi-nginx ./nginx
  - docker build 1234567891993/multi-server ./server
  - docker build 1234567891993/multi-worker ./worker
#Log to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#TAKE IMAGE AND PUSH IT DOCKER HUB
  - docker push  1234567891993/multi-client
  - docker push  1234567891993/multi-nginx
  - docker push  1234567891993/multi-server
  - docker push  1234567891993/multi-worker
