language: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t 1234567892018/react-test -f ./client/Dockerfile ./client


script:
  - docker run 1234567892018/react-test npm  test -- --coverage

after_success:
  - docker build 1234567892018/multi-client ./client
  - docker build 1234567892018/multi-nginx ./nginx
  - docker build 1234567892018/multi-server ./server
  - docker build 1234567892018/multi-worker ./worker
#Log to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#TAKE IMAGE AND PUSH IT DOCKER HUB
  - docker push  1234567892018/multi-client
  - docker push  1234567892018/multi-nginx
  - docker push  1234567892018/multi-server
  - docker push  1234567892018/multi-worker
