language: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t 1234567892018/react-test -f ./client/Dockerfile  ./client
script:
  - docker build -t 1234567892018/multi-client  -f ./client/Dockerfile   ./client
  - docker build -t 1234567892018/multi-nginx  -f  ./nginx/Dockerfile   ./nginx
  - docker build -t 1234567892018/multi-server -f  ./server/Dockerfile   ./server
  - docker build -t 1234567892018/multi-worker -f  ./worker/Dockerfile   ./worker
    #Log to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #TAKE IMAGE AND PUSH IT DOCKER HUB
after_success:
  - docker push  1234567892018/multi-client
  - docker push  1234567892018/multi-nginx
  - docker push  1234567892018/multi-server
  - docker push  1234567892018/multi-worker

deploy:
  provider:  elasticbeanstalk
  region: us-west-1
  app: multi-docker-contaier
  env: Multidockercontaier-env
  bucket_name: elasticbeanstalk-us-west-1-784806628404
  bucket_path: docker-multi
  edge: true
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
    #secure: $AWS_SECRET_KEY
#AWS_ACCESS_KEY=AKIA3NOQ6ZQ2JUR4ZJ6E
#AWS_SECRET_KEY=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
